warmRuns: 7
waitBetweenRuns: 2000
timeout: 30000
headless: true
scenarios:
  - full
  - no-third-party
  - no-tracking-only
network:
  throttle: true
  profile: "cable-10"
lighthouse:
  enabled: true
  runs: 5
  flags:
    - "--chrome-flags=--headless"
httpTiming:
  enabled: true
  runs: 20
  waitBetweenRuns: 500
blocklists:
  thirdParty:
    - "*.doubleclick.net"
    - "*.google-analytics.com"
    - "*.googletagmanager.com"
    - "*.facebook.net"
    - "*.facebook.com"
    - "*.hotjar.com"
    - "*.segment.com"
    - "*.tiktok.com"
    - "*.twitter.com"
    - "*.x.com"
    - "*.intercom.io"
    - "*.zendesk.com"
    - "*.crisp.chat"
    - "*.stripe.com"
    - "*.paypal.com"
    - "*.youtube.com"
    - "*.instagram.com"
    - "*.linkedin.com"
    - "stats.unicef.de"
  criticalThirdParty:
    - "*.usercentrics.eu"
    - "*.frcapi.com"
  trackingOnly:
    - "*.google-analytics.com"
    - "*.googletagmanager.com"
    - "*.facebook.net"
    - "*.hotjar.com"
    - "*.segment.com"
    - "*.tiktok.com"
    - "*.twitter.com"
    - "*.x.com"
    - "connect.facebook.net"
    - "*.doubleclick.net"
    - "*.abtasty.com"
    - "*.optimizely.com"
    - "*.vwo.com"
    - "*.etracker.com"
    - "*.matomo.cloud"
    - "*.piano.io"
    - "stats.unicef.de"
